<template>
    <div class="ConnectedViewshed">
        <SidePanel>
            <SourceList
                class="SidePanel__row"
                :source="source"
                :groups="SUPPORTED_SOURCES"
                :onChange="onSourceChange"
            />

            <div class="SidePanel__row ConnectedViewshed__linestring">
                <span class="ConnectedViewshed__rowCaption">Line String</span>
                <span v-if="!points.length" class="ConnectedViewshed__linestringPlaceholder">Click map anywhere to start drawing a line <i class="fa fa-arrow-right"/></span>

                <div v-if="points.length" class="ConnectedViewshed__linestringCoordinates">
                    <div class="ConnectedViewshed__linestringCoordinate" v-for="point in points">
                        {{ point.longitude | rounded }}, {{ point.latitude | rounded }}
                    </div>

                    <button
                        class="ConnectedViewshed__recenterButton"
                        title="Show this linestring on the map"
                        @click="onRecenterClick">
                        <i class="fa fa-map-marker"/>
                    </button>
                </div>
            </div>

            <NumberRange
                class="SidePanel__row"
                caption="Inner Radius (m)"
                :value="innerRadius"
                :min="1"
                :max="1000"
                :onChange="onInnerRadiusChange"
            />

            <NumberRange
                class="SidePanel__row"
                caption="Outer Radius (m)"
                :value="outerRadius"
                :min="1"
                :max="500"
                :onChange="onOuterRadiusChange"
            />

            <NumberRange
                class="SidePanel__row"
                caption="Start Azimuth (°)"
                :value="startAzimuth"
                :min="0"
                :max="360"
                :onChange="onStartAzimuthChange"
            />

            <NumberRange
                class="SidePanel__row"
                caption="End Azimuth (°)"
                :value="endAzimuth"
                :min="0"
                :max="360"
                :onChange="onEndAzimuthChange"
            />

            <NumberRange
                class="SidePanel__row"
                caption="Observer Height (m)"
                :value="observerHeight"
                :min="MIN_ALTITUDE"
                :max="MAX_ALTITUDE"
                :onChange="onObserverHeightChange"
            />

            <NumberRange
                class="SidePanel__row"
                caption="Target Height (m)"
                :value="targetHeight"
                :min="MIN_ALTITUDE"
                :max="MAX_ALTITUDE"
                :onChange="onTargetHeightChange"
            />

            <label class="SidePanel__row ConnectedViewshed__name">
                <span class="ConnectedViewshed__rowCaption">Analytic Name</span>
                <input v-model="name" :placeholder="autogeneratedName"/>
            </label>

            <div class="ConnectedViewshed__controls">
                <BigButton :disabled="!canSubmit" :onClick="createAnalytic">
                    Create Analytic
                </BigButton>
            </div>

            <RunningAnalyticsList/>
        </SidePanel>

        <LoadingMask
            class="ConnectedViewshed__loadingMask"
            caption="Submitting for processing.  Please wait."
            v-if="isSubmitting"
        />
    </div>
</template>

<script>
    import axios from 'axios'
    import moment from 'moment'
    import { mapActions, mapMutations } from 'vuex'

    import BigButton from '../BigButton.vue'
    import LoadingMask from '../LoadingMask.vue'
    import NumberRange from '../NumberRange.vue'
    import RunningAnalyticsList from '../RunningAnalyticsList.vue'
    import SidePanel from '../SidePanel.vue'
    import SourceList from '../SourceList.vue'

    import * as MapDelegate from './map-delegate'

    import {
        SOURCE_GROUP_ELEVATION,
        MIN_ALTITUDE,
        MAX_ALTITUDE,
    } from '../../constants'


    export default {
        LABEL: 'Connected Viewshed',

        components: {
            BigButton,
            LoadingMask,
            NumberRange,
            RunningAnalyticsList,
            SidePanel,
            SourceList,
        },

        data() {
            return {
                MAX_ALTITUDE,
                MIN_ALTITUDE,
                SUPPORTED_SOURCES: [SOURCE_GROUP_ELEVATION],
                draftedOn: moment.now(),
                endAzimuth: 360,
                innerRadius: 100,
                isSubmitting: false,
                name: '',
                observerHeight: 3,
                outerRadius: 500,
                points: [],
                source: '',
                startAzimuth: 0,
                targetHeight: MIN_ALTITUDE,
            }
        },

        mounted() {
            MapDelegate.activate({
                onPointsChanged: this.onPointsChanged,
            })
            MapDelegate.renderPoints(this.points)
        },

        beforeDestroy() {
            MapDelegate.deactivate()
        },

        computed: {
            autogeneratedName() {
                return [
                    'ConnectedViewshed',
                    moment(this.draftedOn).format('YYYYMMDDHHmm'),  // User's local timezone
                ].join(':')
            },

            canSubmit() {
                return this.source
                    && this.points.length
                    && this.innerRadius < this.outerRadius
            },
        },

        filters: {
            rounded(n) {
                return Math.round(n * 1000) / 1000
            },
        },

        methods: {
            ...mapMutations({
                'onError': 'APPEND_ERROR',
            }),

            ...mapActions({
                'onAnalyticCreated': 'appendNewAnalytic',
            }),

            createAnalytic() {
            },

            onRecenterClick() {
                MapDelegate.recenter()
            },

            onObserverHeightChange(value) {
                this.observerHeight = value
            },

            onPointsChanged(points) {
                this.points = points
                MapDelegate.renderPoints(points)
            },

            onInnerRadiusChange(value) {
                this.innerRadius = value
            },

            onOuterRadiusChange(value) {
                this.outerRadius = value
            },

            onStartAzimuthChange(value) {
                this.startAzimuth = value
            },

            onEndAzimuthChange(value) {
                this.endAzimuth = value
            },

            onSourceChange(value) {
                this.source = value
            },

            onTargetHeightChange(value) {
                this.targetHeight = value
            },
        },
    }
</script>

<style>
    .ConnectedViewshed__rowCaption,
    .ConnectedViewshed .SourceList__caption,
    .ConnectedViewshed .NumberRange__caption {
        display: block;
        margin-bottom: .15em;
        min-width: 100px;
    }

    .ConnectedViewshed__name input {
        width: 100%;
    }

    .ConnectedViewshed__linestringPlaceholder {
        display: block;
        color: #555;
        text-align: center;
    }

    .ConnectedViewshed__linestringCoordinates {
        position: relative;
        padding-right: 45px;
        min-height: 30px;
    }

    .ConnectedViewshed__linestringCoordinate {
        text-align: right;
        font-size: 16px;
        font-weight: 100;
    }

    .ConnectedViewshed__recenterButton {
        position: absolute;
        top: 0;
        right: 0;
        display: inline-block;
        margin-left: .5em;
        vertical-align: text-bottom;
        background-color: #263238;
        border: none;
        color: white;
        cursor: pointer;
        font-size: 14px;
        border-radius: 2px;
        width: 30px;
        height: 30px;
        text-align: center;
    }

    .ConnectedViewshed__recenterButton:hover {
        background-color: hsl(200, 40%, 25%);  /* Based on LimedSpruce */
    }

    .ConnectedViewshed__controls {
        padding: 30px;
        background-color: #1a2327;
        border-top: 1px solid #333;
        border-bottom: 1px solid #333;
    }

    .ConnectedViewshed__loadingMask {
        z-index: 10;
    }

    .ConnectedViewshed__mapLinestring {
        stroke-width: 2;
        stroke-dasharray: 10 10;
        stroke: #50e3c2;
        animation: ConnectedViewshed__mapLinestring--blink infinite linear 3s;
    }

    @keyframes ConnectedViewshed__mapLinestring--blink {
        from { fill-opacity: 1; stroke-dashoffset: 0; }
        to { fill-opacity: .2; stroke-dashoffset: 20; }
    }
</style>
