<template>
    <div class="GeoRing">
        <SidePanel>
            <SourceList
                class="SidePanel__row"
                :source="source"
                :groups="SUPPORTED_SOURCES"
                :onChange="onSourceChange"
            />

            <FileUploader
                class="SidePanel__row"
                :onChange="fetchAggregates"
            />

            <DateRange
                class="SidePanel__row"
                :onChange="onDateFilterChange"
            />

            <label class="SidePanel__row GeoRing__name">
                <span class="GeoRing__rowCaption">Analytic Name</span>
                <input v-model.trim="name" :placeholder="autogeneratedName"/>
            </label>

            <div class="GeoRing__controls">
                <table class="GeoRing__metrics">
                    <tbody>
                        <tr>
                            <th>Records Selected</th>
                            <td>{{ totalSelectedFilteredRecords }} (of {{totalFilteredRecords}} matches)</td>
                        </tr>
                        <tr>
                            <th>Total Records</th>
                            <td>{{ totalRecords }}</td>
                        </tr>
                    </tbody>
                </table>

                <BigButton :disabled="!canSubmit" @click="createAnalytic">
                    Create Analytic
                </BigButton>
            </div>

            <RunningAnalyticsList/>
        </SidePanel>

        <BottomPanel class="GeoRing__bottomPanel">
            <table>
                <thead>
                <tr>
                    <th class="GeoRing__checkboxColumn" @click="toggleSelectAll"><input type="checkbox" :disabled="sortedAggregates.length === 0" :checked="isEveryRowSelected" @click.stop="toggleSelectAll"/></th>
                    <th class="GeoRing__identifierColumn" :class="{ 'sorted': sort.field === 'identifier' }" @click="changeSort('identifier')">Identifier <SortCaret :sort="sort" activeWhen="identifier"/></th>
                    <th class="GeoRing__dateColumn" :class="{ 'sorted': sort.field === 'min_date' }" @click="changeSort('min_date')">First Heard <SortCaret :sort="sort" activeWhen="min_date"/></th>
                    <th class="GeoRing__dateColumn" :class="{ 'sorted': sort.field === 'max_date' }" @click="changeSort('max_date')">Last Heard <SortCaret :sort="sort" activeWhen="max_date"/></th>
                    <th class="GeoRing__countColumn" :class="{ 'sorted': sort.field === 'count' }" @click="changeSort('count')">Count <SortCaret :sort="sort" activeWhen="count"/></th>
                    <th :class="{ 'sorted': sort.field === 'file_names' }" @click="changeSort('file_names')">Filename(s) <SortCaret :sort="sort" activeWhen="file_names"/></th>
                </tr>
                <tr class="GeoRing__keywordFilters">
                    <td class="GeoRing__checkboxColumn"><i class="fa fa-filter"/></td>
                    <td class="GeoRing__identifierColumn" :class="{ 'sorted': sort.field === 'identifier' }"><input placeholder="Filter by keyword" v-model.lazy.trim="filters.identifier"/></td>
                    <td class="GeoRing__dateColumn" :class="{ 'sorted': sort.field === 'min_date' }"></td>
                    <td class="GeoRing__dateColumn" :class="{ 'sorted': sort.field === 'max_date' }"></td>
                    <td class="GeoRing__countColumn" :class="{ 'sorted': sort.field === 'count' }"></td>
                    <td :class="{ 'sorted': sort.field === 'file_names' }"><input placeholder="Filter by keyword" v-model.lazy.trim="filters.filename"/></td>
                </tr>
                </thead>
                <tbody>
                <tr v-for="aggregate in sortedAggregates" :class="{ 'isSelected': aggregate.selected }" @click="() => toggleSelect(aggregate)">
                    <td class="GeoRing__checkboxColumn"><input type="checkbox" v-model="aggregate.selected" @click.stop /></td>
                    <td class="GeoRing__identifierColumn" :class="{ 'sorted': sort.field === 'identifier' }">{{ aggregate.identifier }} <span class="GeoRing__quickFilter" title="Show only this identifier" @click.stop @click="() => filters.identifier = filters.identifier === aggregate.identifier ? '' : aggregate.identifier"><i class="fa fa-filter"/></span></td>
                    <td class="GeoRing__dateColumn" :class="{ 'sorted': sort.field === 'min_date' }" :title="'First Heard: ' + aggregate.min_date">{{ aggregate.min_date | formatDateTime }}</td>
                    <td class="GeoRing__dateColumn" :class="{ 'sorted': sort.field === 'max_date' }" :title="'Last Heard: ' + aggregate.max_date">{{ aggregate.max_date | formatDateTime }}</td>
                    <td class="GeoRing__countColumn" :class="{ 'sorted': sort.field === 'count' }">{{ aggregate.count }}</td>
                    <td :class="{ 'sorted': sort.field === 'file_names' }">{{ aggregate.file_names.join(', ') }}</td>
                </tr>
                <tr v-if="!inflightAggregateRequests && !sortedAggregates.length">
                    <td colspan="7" class="GeoRing__aggregatesPlaceholder">No records match selected filtering criteria</td>
                </tr>
                </tbody>
            </table>

            <div
                class="GeoRing__fitMapContentsButton"
                :class="{'GeoRing__fitMapContentsButton--disabled': !sortedAggregates.length}"
                @click="() => fitMapContents()">
                <i class="fa fa-globe"/> Fit all on Map
            </div>

            <LoadingMask
                class="GeoRing__loadingMask"
                caption="Filtering records.  Please wait."
                small
                v-if="inflightAggregateRequests"
            />
        </BottomPanel>

        <LoadingMask
            class="GeoRing__loadingMask"
            caption="Submitting for processing.  Please wait."
            v-if="isSubmitting"
        />
    </div>
</template>

<script>
    import { mapActions, mapMutations } from 'vuex'
    import axios from 'axios'
    import moment from 'moment'

    import BottomPanel from '../BottomPanel.vue'
    import BigButton from '../BigButton.vue'
    import ErrorMask from '../ErrorMask.vue'
    import LoadingMask from '../LoadingMask.vue'
    import RunningAnalyticsList from '../RunningAnalyticsList.vue'
    import SidePanel from '../SidePanel.vue'
    import SourceList from '../SourceList.vue'

    import DateRange from './DateRange.vue'
    import FileUploader from './FileUploader.vue'
    import SortCaret from './SortCaret.vue'

    import * as MapDelegate from './map-delegate'

    import {SOURCE_GROUP_ELEVATION} from '../../constants'

    export default {
        LABEL: 'GeoRing Batch Processing',

        components: {
            BottomPanel,
            DateRange,
            ErrorMask,
            FileUploader,
            RunningAnalyticsList,
            BigButton,
            LoadingMask,
            SidePanel,
            SortCaret,
            SourceList,
        },

        mounted() {
            MapDelegate.activate({
                onPointClick: this.onPointClick,
            })
        },

        beforeDestroy() {
            MapDelegate.deactivate()
        },

        filters: {
            'formatDateTime'(timestamp) {
                return moment.utc(timestamp).format('MM/DD/YYYY HH:MM\\Z')
            },
        },

        data() {
            return {
                SUPPORTED_SOURCES: [SOURCE_GROUP_ELEVATION],
                aggregates: [],
                filters: {
                    identifier: '',
                    minDate: '',
                    maxDate: '',
                    filename: '',
                },
                name: '',
                sort: {
                    field: 'identifier',
                    ascending: true,
                },
                source: '',
                draftedOn: new Date(),
                totalRecords: 0,
                inflightAggregateRequests: 0,  // refcount as these may come in rapid succession
                isSubmitting: false,
            }
        },

        computed: {
            autogeneratedName() {
                return [
                    'GeoRing',
                    moment(this.draftedOn).format('YYYYMMDDHHmm'),  // User's local timezone
                ].join(':')
            },

            canSubmit() {
                return !this.isSubmitting
                    && !this.inflightAggregateRequests
                    && !this.isMissingSelectedAggregates
            },

            isEveryRowSelected() {
                console.debug('[GeoRing] Recomputing `isEveryRowSelected`')
                return this.selectedAggregates.length === this.aggregates.length
            },

            isMissingSelectedAggregates() {
                return this.selectedAggregates.length === 0
            },

            selectedAggregates() {
                console.debug('[GeoRing] Recomputing `selectedAggregates`')
                return this.aggregates.filter(r => r.selected)
            },

            sortedAggregates() {
                const {field, ascending} = this.sort
                return this.aggregates
                    .slice()
                    .sort((a, b) => {
                        const aComparable = Array.isArray(a[field]) ? a[field].join(',') : a[field]
                        const bComparable = Array.isArray(b[field]) ? b[field].join(',') : b[field]
                        if (aComparable > bComparable) {
                            return ascending ? 1 : -1
                        }
                        if (aComparable < bComparable) {
                            return ascending ? -1 : 1
                        }
                        return 0
                    })
            },

            totalFilteredRecords() {
                return this.aggregates.reduce((subtotal, agg) => subtotal + agg.count, 0)
            },

            totalSelectedFilteredRecords() {
                return this.selectedAggregates.reduce((subtotal, agg) => subtotal + agg.count, 0)
            },
        },

        watch: {
            'filters.identifier'() {
                this.fetchAggregates()
            },

            'filters.filename'() {
                this.fetchAggregates()
            },

            selectedAggregates() {
                MapDelegate.renderPoints(this.aggregates)
            },
        },

        methods: {
            ...mapMutations({
                'onError': 'APPEND_ERROR',
            }),

            ...mapActions({
                'onAnalyticCreated': 'appendNewAnalytic',
            }),

            changeSort(field) {
                // Reverse direction
                if (field === this.sort.field) {
                    this.sort.ascending = !this.sort.ascending
                    return
                }

                // Change field
                switch (field) {
                case 'identifier':
                case 'min_date':
                case 'max_date':
                case 'count':
                case 'file_names':
                    this.sort.field = field
                    this.sort.ascending = true
                    break
                default:
                    console.warn('[GeoRing] Unknown sort field "%s"', field)
                    break
                }
            },

            fetchAggregates() {
                const params = {
                    'file_name':  this.filters.filename,
                    'identifier': this.filters.identifier,
                    'min_date':   this.filters.minDate,
                    'max_date':   this.filters.maxDate,
                }

                const cancelToken = new axios.CancelToken(cancel => {
                    if (this.cancelInflightAggregateRequest) {
                        this.cancelInflightAggregateRequest()
                    }
                    this.cancelInflightAggregateRequest = cancel
                })

                this.inflightAggregateRequests++
                axios.get('/api/georing/aggregates', { params, cancelToken })
                    .then(response => {
                        this.inflightAggregateRequests = Math.max(0, this.inflightAggregateRequests - 1)

                        this.totalRecords = response.data.total_count
                        this.aggregates = response.data.aggregates.map(a => {
                            a.selected = true
                            return a
                        })
                    })
                    .catch(err => {
                        this.inflightAggregateRequests = Math.max(0, this.inflightAggregateRequests - 1)

                        if (axios.isCancel(err)) {
                            return
                        }

                        this.onError({
                            heading: 'Could not retrieve aggregates',
                            message: `A system error prevented the listing of record aggregates. If this
                                      problem persists, please contact an XTerrain administrator for
                                      technical support.`,
                        })
                    })
            },

            onDateFilterChange(fromDate, toDate) {
                this.filters.minDate = fromDate
                this.filters.maxDate = toDate
                this.fetchAggregates()
            },

            onPointClick(identifier) {
                const record = this.aggregates.find(r => r.identifier === identifier)
                record.selected = !record.selected
            },

            onSourceChange(value) {
                this.source = value
            },

            fitMapContents() {
                if (!this.selectedAggregates.length) {
                    return  // Nothing to pan to
                }
                MapDelegate.fitContents()
            },

            createAnalytic() {
                const request = {
                    'name': this.name || this.autogeneratedName,
                    'source': this.source,
                    'filters': {
                        'file_name':    this.filters.filename,
                        'identifier':   this.filters.identifier,
                        'identifiers':  this.selectedAggregates.map(r => r.identifier),
                        'min_date':     this.filters.minDate,
                        'max_date':     this.filters.maxDate,
                    },
                }
                console.debug('[GeoRing] Submitting request for processing:\n%s', JSON.stringify(request, null, 2))
                this.isSubmitting = true
                axios.post('/api/georing/new_analytic', request)
                    .then(response => {
                        this.draftedOn = new Date()
                        this.isSubmitting = false

                        this.onAnalyticCreated(response.data.analytic)
                    })
                    .catch(err => {
                        this.isSubmitting = false
                        const {response} = err
                        if (response) {
                            this.onError({
                                heading: 'Could not submit records for processing',
                                message: response.status >= 400 && response.status < 500
                                    ? `The server rejected your request: "${response.data.error}"`
                                    : `A server or network error prevented the submission of these records
                                       for processing.  If this problem persists, please contact an
                                       XTerrain administrator for technical support.`
                            })
                        }
                        else {
                            this.onError({
                                heading: 'Application error has occurred',
                                message: `An application error is preventing normal operation.  If this
                                          problem persists, please contact an XTerrain administrator for
                                          technical support.  (${err.message})`
                            })
                        }
                    })
            },

            toggleSelect(aggregate) {
                aggregate.selected = !aggregate.selected
            },

            toggleSelectAll() {
                const value = !this.isEveryRowSelected
                this.aggregates.forEach(aggregate => {
                    aggregate.selected = value
                })
            },
        },
    }
</script>

<style>
    .GeoRing__bottomPanel {
        overflow: scroll;
    }

    .GeoRing__bottomPanel table {
        min-width: 100%;
        border-collapse: collapse;
        border: none;
        font-size: 12px;
    }

    .GeoRing__bottomPanel thead th {
        background-color: #607D8B;
        padding: 12px 12px 4px;
        vertical-align: bottom;
        text-align: left;
        white-space: nowrap;
        cursor: pointer;
    }

    .GeoRing__bottomPanel thead th.sorted {
        background-color: hsl(187, 50%, 64%);
        box-shadow:
            inset 1px 0 hsl(187, 50%, 75%),
            inset -1px 0 hsl(187, 50%, 75%);  /* Based on PacificBlue */
    }

    .GeoRing__keywordFilters td {
        border-top: 1px solid hsl(200, 18%, 50%);  /* Based on Gothic */
        background-color: hsl(200, 18%, 30%);  /* Based on Gothic */
        color: #4CAF50;
        font-size: 12px;
    }

    .GeoRing__keywordFilters .sorted {
        border-top: 1px solid hsl(187, 50%, 70%);  /* Based on PacificBlue */
        background-color: hsl(187, 50%, 60%);  /*Based on PacificBlue */
        color: white;
    }

    .GeoRing__keywordFilters .fa {
        color: hsl(200, 18%, 75%);  /* Based on Gothic */
    }

    .GeoRing__keywordFilters input {
        padding: 5px 10px;
        width: 100%;
        margin: 0;
        border: none;
        background-color: transparent;
        box-shadow: none !important;
        color: inherit;
        font-size: inherit;
    }

    .GeoRing__keywordFilters input:hover {
        background-color: rgba(255,255,255, .1);
    }

    .GeoRing__keywordFilters input::-webkit-input-placeholder {
        color: rgba(255,255,255, .3);
    }

    .GeoRing__keywordFilters input::placeholder {
        color: rgba(255,255,255, .3);
    }

    .GeoRing__keywordFilters input:focus {
        border: none;
        background-color: hsla(122, 39%, 49%, .3);  /* Based on Fern */
        color: white;
        box-shadow: none !important;
    }

    .GeoRing__fitMapContentsButton {
        z-index: 5;
        position: absolute;
        top: 5px;
        right: 35px;
        height: 24px;
        padding: 0 .5em;
        line-height: 24px;
        text-align: center;
        font-size: 14px;
        background-color: rgba(255,255,255, .15);
        border-radius: 2px;
        cursor: pointer;
    }

    .GeoRing__fitMapContentsButton:hover:not(.GeoRing__fitMapContentsButton--disabled) {
        background-color: rgba(255,255,255, .3);
    }

    .GeoRing__fitMapContentsButton--disabled {
        opacity: .3;
        cursor: not-allowed;
    }

    .GeoRing__bottomPanel tbody tr {
        color: #757575;
    }

    .GeoRing__bottomPanel tbody tr:first-child {
        border-top: 1px solid white;
    }

    .GeoRing__bottomPanel tbody tr:nth-child(odd) {
        background-color: #222;
    }

    .GeoRing__bottomPanel tbody td {
        padding: 5px 1em;
        vertical-align: top;
    }

    .GeoRing__bottomPanel .isSelected {
        background-color: #263238 !important;
        color: white !important;
    }

    .GeoRing__bottomPanel .isSelected:nth-child(odd) {
        background-color: hsl(200, 19%, 22%) !important;  /* Based on LimedSpruce */
    }

    .GeoRing__bottomPanel tbody td.sorted {
        background-color: hsl(187, 30%, 32%) !important;  /* Based on PacificBlue */
        color: white !important;
        box-shadow:
            inset 1px 0 hsl(187, 30%, 40%),
            inset -1px 0 hsl(187, 30%, 40%);  /* Based on PacificBlue */
    }

    .GeoRing__bottomPanel tbody tr:nth-child(odd) .sorted {
        background-color: hsl(187, 30%, 35%) !important;  /* Based on PacificBlue */
    }

    .GeoRing__checkboxColumn {
        width: 2em;
        text-align: center !important;
    }

    .GeoRing__identifierColumn {
        word-break: break-all;
        width: 15em;
    }

    .GeoRing__dateColumn {
        width: 9em;
    }

    .GeoRing__countColumn {
        width: 4.5em;
    }

    .GeoRing__quickFilter {
        cursor: pointer;
        display: inline-block;
        padding: 0 .25em;
        text-align: center;
        opacity: 0;
    }

    .GeoRing__bottomPanel tbody tr:hover .GeoRing__quickFilter {
        opacity: .4;
    }

    .GeoRing__quickFilter:hover {
        opacity: 1 !important;
    }

    .GeoRing__aggregatesPlaceholder {
        padding-top: 10vh !important;
        color: #444;
        background-color: #111 !important;
        text-shadow: -1px -1px rgba(0,0,0, .3);
        vertical-align: middle;
        text-align: center;
        font-size: 1.5em;
        font-weight: 100;
    }

    .GeoRing__cluster {
        border-radius: 50%;
        background: hsla(200, 19%, 18%, .6);  /* Based on LimedSpruce */
        box-shadow: 0 0 0 10px hsla(200, 19%, 18%, .3);
        color: white;
        text-shadow: 1px 1px rgba(0,0,0,.3);
        transition: transform .3s ease-out, opacity .3s ease-in;
        width: 40px;
        height: 40px;
    }

    .GeoRing__cluster div {
        line-height: 40px;
        text-align: center;
        font-weight: 200;
        font-size: 11px;
    }

    .GeoRing__clusterBounds {
        stroke-width: 0;
        fill: rgba(255,255,255, .5);
        animation: infinite alternate GeoRing__clusterBounds--blink linear 1s;
    }

    @keyframes GeoRing__clusterBounds--blink {
        from { fill-opacity: 1; }
        to { fill-opacity: 0; }
    }

    .GeoRing__point {
        stroke: #757575;
        fill: #757575;
        fill-opacity: 1;
        stroke-width: 10px;
        transition: stroke-width .5s cubic-bezier(0, 1.52, 0.32, 1.53);
    }

    .GeoRing__point:hover {
        stroke-width: 30px;
    }

    .GeoRing__point--isSelected {
        stroke: #4CAF50;
        fill: #4CAF50;
    }

    .GeoRing__point--isRelated {
        stroke: #FDD835;
        stroke-opacity: .5;
        stroke-width: 40px;
    }

    .GeoRing__pointTooltip {
        font-weight: bold;
    }

    .GeoRing .SourceList__caption,
    .GeoRing .FileUploader__caption,
    .GeoRing__rowCaption {
        display: block;
        margin-bottom: .15em;
        min-width: 100px;
    }

    .GeoRing__controls {
        padding: 30px;
        background-color: #1a2327;
        border-top: 1px solid #333;
        border-bottom: 1px solid #333;
    }

    .GeoRing__metrics {
        margin-bottom: 30px;
        width: 100%;
        font-size: 12px;
        border-collapse: collapse;
    }

    .GeoRing__metrics th,
    .GeoRing__metrics td {
        padding: .5em;
        vertical-align: top;
    }

    .GeoRing__metrics th {
        width: 50%;
        text-align: right;
        color: hsl(179, 15%, 30%);  /* Based on GulfStream */
        font-weight: normal;
    }

    .GeoRing__metrics td {
        color: hsl(179, 25%, 65%);  /* Based on GulfStream */
        font-weight: bold;
    }

    .GeoRing__name input {
        width: 100%;
    }

    .GeoRing__loadingMask {
        z-index: 10;
    }
</style>
