<template>
    <div class="GeoRing">
        <SidePanel>
            <SourceList
                class="SidePanel__row"
                :source="source"
                :groups="SUPPORTED_SOURCES"
                :onChange="onSourceChange"
            />

            <div class="SidePanel__row GeoRing__point">
                <span class="GeoRing__rowCaption">Point</span>
                <span v-if="!point" class="GeoRing__pointPlaceholder">Click map anywhere to draw a point <i class="fa fa-arrow-right"/></span>

                <div v-if="point" class="GeoRing__pointCoordinates">
                    {{ point.longitude | rounded }}, {{ point.latitude | rounded }}

                    <button
                        class="GeoRing__recenterButton"
                        title="Show this point on the map"
                        @click="onRecenterClick">
                        <i class="fa fa-map-marker"/>
                    </button>
                </div>
            </div>

            <NumberRange
                class="SidePanel__row"
                caption="Inner Radius (m)"
                :value="innerRadius"
                :min="1"
                :max="outerRadius"
                :onChange="onInnerRadiusChange"
            />

            <NumberRange
                class="SidePanel__row"
                caption="Outer Radius (m)"
                :value="outerRadius"
                :min="innerRadius"
                :max="5000"
                :onChange="onOuterRadiusChange"
            />

            <NumberRange
                class="SidePanel__row"
                caption="Altitude (m)"
                :value="altitude"
                :min="MIN_ALTITUDE"
                :max="MAX_ALTITUDE"
                :onChange="onAltitudeChange"
            />

            <label class="SidePanel__row GeoRing__name">
                <span class="GeoRing__rowCaption">Analytic Name</span>
                <input v-model="name" :placeholder="autogeneratedName"/>
            </label>

            <div class="GeoRing__controls">
                <BigButton :disabled="!canSubmit" :onClick="createAnalytic">
                    Create Analytic
                </BigButton>
            </div>

            <RunningAnalyticsList/>
        </SidePanel>

        <LoadingMask
            class="GeoRing__loadingMask"
            caption="Submitting for processing.  Please wait."
            v-if="isSubmitting"
        />
    </div>
</template>

<script>
    import axios from 'axios'
    import moment from 'moment'
    import { mapActions, mapMutations } from 'vuex'

    import BigButton from '../BigButton.vue'
    import LoadingMask from '../LoadingMask.vue'
    import NumberRange from '../NumberRange.vue'
    import RunningAnalyticsList from '../RunningAnalyticsList.vue'
    import SidePanel from '../SidePanel.vue'
    import SourceList from '../SourceList.vue'

    import * as MapDelegate from './map-delegate'

    import {
        SOURCE_GROUP_ELEVATION,
        MIN_ALTITUDE,
        MAX_ALTITUDE,
    } from '../../constants'


    export default {
        LABEL: 'GeoRing',

        components: {
            BigButton,
            LoadingMask,
            NumberRange,
            RunningAnalyticsList,
            SidePanel,
            SourceList,
        },

        data() {
            return {
                MAX_ALTITUDE,
                MIN_ALTITUDE,
                SUPPORTED_SOURCES: [SOURCE_GROUP_ELEVATION],
                altitude: MIN_ALTITUDE,
                draftedOn: moment.now(),
                innerRadius: 100,
                isSubmitting: false,
                name: '',
                outerRadius: 1000,
                point: null,
                source: '',
            }
        },

        mounted() {
            MapDelegate.activate({
                onPointCreated: this.onPointCreated,
            })
        },

        beforeDestroy() {
            MapDelegate.deactivate()
        },

        computed: {
            autogeneratedName() {
                return [
                    'GeoRing',
                    moment(this.draftedOn).format('YYYYMMDDHHmm'),  // User's local timezone
                ].join(':')
            },

            canSubmit() {
                return this.source
                    && this.point
                    && this.innerRadius
                    && this.outerRadius
            },
        },

        filters: {
            rounded(n) {
                return Math.round(n * 1000) / 1000
            },
        },

        methods: {
            ...mapMutations({
                'onError': 'APPEND_ERROR',
            }),

            ...mapActions({
                'onAnalyticCreated': 'appendNewAnalytic',
            }),

            createAnalytic() {
                const request = {
                    'altitude':        this.altitude,
                    'latitude':        this.point.latitude,
                    'inner_radius':    this.innerRadius,
                    'longitude':       this.point.longitude,
                    'name':            this.name || this.autogeneratedName,
                    'outer_radius':    this.outerRadius,
                    'source':          this.source,
                }

                console.debug('[GeoRing] Submitting request for processing:\n%s', JSON.stringify(request, null, 4))

                this.isSubmitting = true

                axios.post('/api/georing/create_analytic', request)
                    .then(response => {
                        this.draftedOn = moment.now()
                        this.isSubmitting = false

                        this.onAnalyticCreated(response.data.analytic)
                    })
                    .catch(err => {
                        this.isSubmitting = false

                        const {response} = err
                        if (response) {
                            this.onError({
                                heading: 'Could not create GeoRing analytic',
                                message: response.status >= 400 && response.status < 500
                                    ? `The server rejected your request: "${response.data.error}"`
                                    : `A server or network error prevented the submission of these records
                                       for processing.  If this problem persists, please contact an
                                       XTerrain administrator for technical support.`
                            })
                        }
                        else {
                            this.onError({
                                heading: 'Application error has occurred',
                                message: `An application error is preventing normal operation.  If this
                                          problem persists, please contact an XTerrain administrator for
                                          technical support.  (${err.message})`
                            })
                        }
                    })
            },

            onAltitudeChange(value) {
                this.altitude = value
            },

            onInnerRadiusChange(value) {
                this.innerRadius = value
            },

            onRecenterClick() {
                MapDelegate.recenter()
            },

            onPointCreated({ latitude, longitude }) {
                this.point = { latitude, longitude }
            },

            onOuterRadiusChange(value) {
                this.outerRadius = value
            },

            onSourceChange(value) {
                this.source = value
            },

            onTargetHeightChange(value) {
                this.targetHeight = value
            },

            rerenderMapFeatures() {
                if (!this.point) {
                    return  // Nothing to do
                }

                MapDelegate.renderPoint({
                    point: this.point,
                    innerRadius: this.innerRadius,
                    outerRadius: this.outerRadius,
                })
            }
        },

        watch: {
            point: 'rerenderMapFeatures',
            innerRadius: 'rerenderMapFeatures',
            outerRadius: 'rerenderMapFeatures',
        },
    }
</script>

<style>
    .GeoRing__rowCaption,
    .GeoRing .SourceList__caption,
    .GeoRing .NumberRange__caption {
        display: block;
        margin-bottom: .15em;
        min-width: 100px;
    }

    .GeoRing__name input {
        width: 100%;
    }

    .GeoRing__pointCoordinates {
        /*margin-top: -20px;*/
        text-align: right;
        font-size: 24px;
        font-weight: 100;
    }

    .GeoRing__pointPlaceholder {
        display: block;
        color: #555;
        text-align: center;
    }

    .GeoRing__recenterButton {
        display: inline-block;
        margin-left: .5em;
        vertical-align: text-bottom;
        background-color: #263238;
        border: none;
        color: white;
        cursor: pointer;
        font-size: 14px;
        border-radius: 2px;
        width: 30px;
        height: 30px;
        text-align: center;
    }

    .GeoRing__recenterButton:hover {
        background-color: hsl(200, 40%, 25%);  /* Based on LimedSpruce */
    }

    .GeoRing__controls {
        padding: 30px;
        background-color: #1a2327;
        border-top: 1px solid #333;
        border-bottom: 1px solid #333;
    }

    .GeoRing__mapRadius {
        animation: GeoRing__mapRadius--marchingAnts infinite linear 3s;
        stroke-width: 2;
        stroke-dasharray: 5 5;
        fill: none;
        stroke: hsla(179, 100%, 75%, .7);  /* Based on GulfStream */
    }

    .GeoRing__mapRadius--inner {
        animation-direction: reverse;
    }

    @keyframes GeoRing__mapRadius--marchingAnts {
        from { stroke-dashoffset: 0; }
        to { stroke-dashoffset: 10; }
    }

    .GeoRing__loadingMask {
        z-index: 10;
    }
</style>
