<template>
    <div class="Hillshade">
        <SidePanel>
            <SourceList
                class="SidePanel__row"
                :source="source"
                :groups="SUPPORTED_SOURCES"
                :onChange="onSourceChange"
            />

            <div class="SidePanel__row Hillshade__rectangle">
                <span class="Hillshade__rowCaption">Rectangle</span>
                <span v-if="!rectangle" class="Hillshade__rectanglePlaceholder">Click map anywhere to start drawing a line <i class="fa fa-arrow-right"/></span>

                <div v-if="rectangle" class="Hillshade__rectangleCoordinates">
                    <div class="Hillshade__rectangleCoordinate">
                        {{ rectangle[0] | rounded }}, {{ rectangle[1] | rounded }}
                    </div>
                    <div class="Hillshade__rectangleCoordinate">
                        {{ rectangle[2] | rounded }}, {{ rectangle[3] | rounded }}
                    </div>

                    <button
                        class="Hillshade__recenterButton"
                        title="Show this rectangle on the map"
                        @click="onRecenterClick">
                        <i class="fa fa-map-marker"/>
                    </button>
                </div>
            </div>

            <NumberRange
                class="SidePanel__row"
                caption="Sun Altitude (°)"
                :min="0"
                :max="360"
                :value="sunAltitude"
                :onChange="onSunAltitudeChange"
            />

            <NumberRange
                class="SidePanel__row"
                caption="Sun Azimuth (°)"
                :min="0"
                :max="360"
                :value="sunAzimuth"
                :onChange="onSunAzimuthChange"
            />

            <label class="SidePanel__row Hillshade__name">
                <span class="Hillshade__rowCaption">Analytic Name</span>
                <input v-model="name" :placeholder="autogeneratedName"/>
            </label>

            <div class="Hillshade__controls">
                <BigButton :disabled="!canSubmit" :onClick="createAnalytic">
                    Create Analytic
                </BigButton>
            </div>

            <RunningAnalyticsList/>
        </SidePanel>

        <LoadingMask
            class="Hillshade__loadingMask"
            caption="Submitting for processing.  Please wait."
            v-if="isSubmitting"
        />
    </div>
</template>

<script>
    import axios from 'axios'
    import moment from 'moment'
    import { mapActions, mapMutations } from 'vuex'

    import BigButton from '../BigButton.vue'
    import LoadingMask from '../LoadingMask.vue'
    import NumberRange from '../NumberRange.vue'
    import RunningAnalyticsList from '../RunningAnalyticsList.vue'
    import SidePanel from '../SidePanel.vue'
    import SourceList from '../SourceList.vue'

    import * as MapDelegate from './map-delegate'

    import {
        SOURCE_GROUP_ELEVATION,
        MIN_ALTITUDE,
        MAX_ALTITUDE,
    } from '../../constants'


    export default {
        LABEL: 'Hillshade',

        components: {
            BigButton,
            LoadingMask,
            NumberRange,
            RunningAnalyticsList,
            SidePanel,
            SourceList,
        },

        data() {
            return {
                MAX_ALTITUDE,
                MIN_ALTITUDE,
                SUPPORTED_SOURCES: [SOURCE_GROUP_ELEVATION],
                draftedOn: moment.now(),
                isSubmitting: false,
                name: '',
                rectangle: null,
                source: '',
                sunAltitude: 45,
                sunAzimuth: 324,
            }
        },

        mounted() {
            MapDelegate.activate({
                onRectangleChanged: this.onRectangleChanged,
            })
        },

        beforeDestroy() {
            MapDelegate.deactivate()
        },

        computed: {
            autogeneratedName() {
                return [
                    'Hillshade',
                    moment(this.draftedOn).format('YYYYMMDDHHmm'),  // User's local timezone
                ].join(':')
            },

            canSubmit() {
                return this.source
                    && this.rectangle
            },
        },

        filters: {
            rounded(n) {
                return Math.round(n * 1000) / 1000
            },
        },

        methods: {
            ...mapMutations({
                'onError': 'APPEND_ERROR',
            }),

            ...mapActions({
                'onAnalyticCreated': 'appendNewAnalytic',
            }),

            createAnalytic() {
                const request = {
                    'name':         this.name || this.autogeneratedName,
                    'bbox':         this.rectangle,
                    'source':       this.source,
                    'sun_altitude': this.sunAltitude,
                    'sun_azimuth':  this.sunAzimuth,
                }

                console.debug('[Hillshade] Submitting request for processing:\n%s', JSON.stringify(request, null, 4))

                this.isSubmitting = true

                axios.post('/api/hillshade/create_analytic', request)
                    .then(response => {
                        this.draftedOn = moment.now()
                        this.isSubmitting = false

                        this.onAnalyticCreated(response.data.analytic)
                    })
                    .catch(err => {
                        this.isSubmitting = false

                        const {response} = err
                        if (response) {
                            this.onError({
                                heading: 'Could not create Hillshade analytic',
                                message: response.status >= 400 && response.status < 500
                                    ? `The server rejected your request: "${response.data.error}"`
                                    : `A server or network error prevented the submission of these records
                                       for processing.  If this problem persists, please contact an
                                       XTerrain administrator for technical support.`
                            })
                        }
                        else {
                            this.onError({
                                heading: 'Application error has occurred',
                                message: `An application error is preventing normal operation.  If this
                                          problem persists, please contact an XTerrain administrator for
                                          technical support.  (${err.message})`
                            })
                        }
                    })
            },

            onRecenterClick() {
                MapDelegate.recenter()
            },

            onRectangleChanged(rectangle) {
                this.rectangle = rectangle
            },

            onSourceChange(value) {
                this.source = value
            },

            rerenderMapRectangle() {
                if (!this.rectangle) {
                    return  // Nothing to do
                }

                MapDelegate.renderRectangle({
                    rectangle: this.rectangle,
                })
            },

            onSunAltitudeChange(value) {
                this.sunAltitude = value
            },

            onSunAzimuthChange(value) {
                this.sunAzimuth = value
            },
        },

        watch: {
            rectangle: 'rerenderMapRectangle',
        },
    }
</script>

<style>
    .Hillshade__rowCaption,
    .Hillshade .SourceList__caption,
    .Hillshade .NumberRange__caption {
        display: block;
        margin-bottom: .15em;
        min-width: 100px;
    }

    .Hillshade__name input {
        width: 100%;
    }

    .Hillshade__rectangleCoordinates {
        /*margin-top: -20px;*/
        text-align: right;
        font-size: 24px;
        font-weight: 100;
    }

    .Hillshade__rectanglePlaceholder {
        display: block;
        color: #555;
        text-align: center;
    }

    .Hillshade__recenterButton {
        display: inline-block;
        margin-left: .5em;
        vertical-align: text-bottom;
        background-color: #263238;
        border: none;
        color: white;
        cursor: pointer;
        font-size: 14px;
        border-radius: 2px;
        width: 30px;
        height: 30px;
        text-align: center;
    }

    .Hillshade__recenterButton:hover {
        background-color: hsl(200, 40%, 25%);  /* Based on LimedSpruce */
    }

    .Hillshade__controls {
        padding: 30px;
        background-color: #1a2327;
        border-top: 1px solid #333;
        border-bottom: 1px solid #333;
    }

    .Hillshade__mapRectangleFootprint {
        animation: Hillshade__mapRectangleFootprint--blink infinite linear 3s;
        stroke-width: 2;
        stroke-dasharray: 10 10;
        fill: hsla(179, 100%, 75%, .5);  /* Based on GulfStream */
        stroke: hsla(179, 100%, 75%, .7);  /* Based on GulfStream */
    }

    @keyframes Hillshade__mapRectangleFootprint--blink {
        from { fill-opacity: 1; stroke-dashoffset: 0; }
        to { fill-opacity: .2; stroke-dashoffset: 20; }
    }

    .Hillshade__loadingMask {
        z-index: 10;
    }
</style>
