<template>
    <div class="Viewshed">
        <SidePanel>
            <SourceList
                class="SidePanel__row"
                :source="source"
                :groups="SUPPORTED_SOURCES"
                :onChange="onSourceChange"
            />

            <label class="SidePanel__row Viewshed__radius">
                <span class="Viewshed__rowCaption">Radius</span>
                <input type="range" v-model="radius" min="0" :max="maxRadius"/>
            </label>

            <label class="SidePanel__row Viewshed__name">
                <span class="Viewshed__rowCaption">Analytic Name</span>
                <input v-model="name" :placeholder="autogeneratedName"/>
            </label>

            <div class="SidePanel__row Viewshed__point">
                <span class="Viewshed__rowCaption">Point</span>
                <div v-if="point" class="Viewshed__pointLatitude">{{ point.latitude }}, {{ point.longitude }}</div>
                <div v-else>Nothing Selected</div>

                <button class="Viewshed__recenterButton" :disabled="!point" @click="onRecenterClick"><i class="fa fa-map-marker"/></button>
            </div>

            <RunningAnalyticsList/>

            <pre>{{ $data }}</pre>
        </SidePanel>
    </div>
</template>

<script>
    import moment from 'moment'
    import RunningAnalyticsList from '../RunningAnalyticsList.vue'
    import SidePanel from '../SidePanel.vue'
    import SourceList from '../SourceList.vue'

    import * as MapDelegate from './map-delegate'

    import {
        SOURCE_ELEVATION,
        SOURCE_HI_RES_ELEVATION,
    } from '../../constants'


    // TODO -- automatically update on source change
    const MAX_RADIUS = {
        [SOURCE_ELEVATION]: 12000,
        [SOURCE_HI_RES_ELEVATION]: 1000,
    }


    export default {
        LABEL: 'Viewshed',

        components: {
            RunningAnalyticsList,
            SidePanel,
            SourceList,
        },

        data() {
            return {
                SUPPORTED_SOURCES: [
                    SOURCE_ELEVATION,
                    SOURCE_HI_RES_ELEVATION,
                ],
                dateDrafted: moment.now(),
                name: '',
                observerHeight: 2.0,
                point: null,
                radius: 12000,
                source: '',
                targetHeight: 0.0,
            }
        },

        mounted() {
            MapDelegate.activate({
                onPointCreated: this.onPointCreated,
            })
        },

        computed: {
            autogeneratedName() {
                return [
                    'Viewshed',
                    moment(this.draftedOn).format('YYYYMMDDHHmm'),  // User's local timezone
                ].join(':')
            },

            maxRadius() {
                const sourceType = SOURCE_ELEVATION  // FIXME -- compute this somehow
                return MAX_RADIUS[sourceType]
            },
        },

        methods: {
            createAnalytic() {
                this.dateDrafted = moment.now()
            },

            onRecenterClick() {
                MapDelegate.recenter()
            },

            onPointCreated({ latitude, longitude }) {
                this.point = { latitude, longitude }
            },

            onSourceChange(value) {
                this.source = value
            },
        },

        watch: {
            point() {
                MapDelegate.renderPoint({
                    point: this.point,
                    radius: this.radius,
                })
            },
            radius() {
                if (!this.point) {
                    return  // Nothing to do
                }

                MapDelegate.renderPoint({
                    point: this.point,
                    radius: this.radius,
                })
            },
        },
    }
</script>

<style>
    .Viewshed__rowCaption {
        display: inline-block;
        min-width: 100px;
    }

    .Viewshed__mapPointFootprint {
        animation: Viewshed__mapPointFootprint--blink infinite linear 3s;
        stroke-width: 2;
        stroke-dasharray: 5 10;
        /*fill: hsla(179, 21%, 61%, 1);  !* Based on GulfStream *!*/
        fill: hsla(179, 100%, 75%, .5);  /* Based on GulfStream */
        stroke: hsla(179, 100%, 75%, .7);  /* Based on GulfStream */
    }

    @keyframes Viewshed__mapPointFootprint--blink {
        from { fill-opacity: 1; stroke-dashoffset: 0; }
        to { fill-opacity: .2; stroke-dashoffset: 15; }
    }
</style>
