<template>
    <div class="Viewshed">
        <SidePanel>
            <SourceList
                class="SidePanel__row"
                :source="source"
                :groups="SUPPORTED_SOURCES"
                :onChange="onSourceChange"
            />

            <div class="SidePanel__row Viewshed__point">
                <span class="Viewshed__rowCaption">Point</span>
                <span v-if="!point" class="Viewshed__pointPlaceholder">Click map anywhere to draw a point <i class="fa fa-arrow-right"/></span>

                <div v-if="point" class="Viewshed__pointCoordinates">
                    {{ point.longitude | rounded }}, {{ point.latitude | rounded }}

                    <button
                        class="Viewshed__recenterButton"
                        title="Show this point on the map"
                        :disabled="!point"
                        @click="onRecenterClick">
                        <i class="fa fa-map-marker"/>
                    </button>
                </div>
            </div>

            <NumberRange
                class="SidePanel__row"
                caption="Radius (m)"
                :value="radius"
                :min="1"
                :max="maxRadius"
                :onChange="onRadiusChange"
            />

            <NumberRange
                class="SidePanel__row"
                caption="Observer Height (m)"
                :value="observerHeight"
                :min="MIN_ALTITUDE"
                :max="MAX_ALTITUDE"
                :onChange="onObserverHeightChange"
            />

            <NumberRange
                class="SidePanel__row"
                caption="Target Height (m)"
                :value="targetHeight"
                :min="MIN_ALTITUDE"
                :max="MAX_ALTITUDE"
                :onChange="onTargetHeightChange"
            />

            <label class="SidePanel__row Viewshed__name">
                <span class="Viewshed__rowCaption">Analytic Name</span>
                <input v-model="name" :placeholder="autogeneratedName"/>
            </label>

            <div class="Viewshed__controls">
                <BigButton :disabled="!canSubmit" :onClick="createAnalytic">
                    Create Analytic
                </BigButton>
            </div>

            <RunningAnalyticsList/>
        </SidePanel>

        <LoadingMask
            class="Viewshed__loadingMask"
            caption="Submitting for processing.  Please wait."
            v-if="isSubmitting"
        />
    </div>
</template>

<script>
    import axios from 'axios'
    import moment from 'moment'
    import { mapActions, mapMutations } from 'vuex'

    import BigButton from '../BigButton.vue'
    import LoadingMask from '../LoadingMask.vue'
    import NumberRange from '../NumberRange.vue'
    import RunningAnalyticsList from '../RunningAnalyticsList.vue'
    import SidePanel from '../SidePanel.vue'
    import SourceList from '../SourceList.vue'

    import * as MapDelegate from './map-delegate'

    import {
        SOURCE_ELEVATION,
        SOURCE_HI_RES_ELEVATION,
        MIN_ALTITUDE,
        MAX_ALTITUDE,
    } from '../../constants'


    const MAX_RADIUS = {
        [SOURCE_ELEVATION]: 12000,
        [SOURCE_HI_RES_ELEVATION]: 1000,
    }


    export default {
        LABEL: 'Viewshed',

        components: {
            BigButton,
            LoadingMask,
            NumberRange,
            RunningAnalyticsList,
            SidePanel,
            SourceList,
        },

        data() {
            return {
                MAX_ALTITUDE,
                MIN_ALTITUDE,
                SUPPORTED_SOURCES: [
                    SOURCE_ELEVATION,
                    SOURCE_HI_RES_ELEVATION,
                ],
                draftedOn: moment.now(),
                isSubmitting: false,
                name: '',
                observerHeight: 500,
                point: null,
                radius: 12000,
                source: '',
                targetHeight: MIN_ALTITUDE,
            }
        },

        mounted() {
            MapDelegate.activate({
                onPointCreated: this.onPointCreated,
            })
        },

        beforeDestroy() {
            MapDelegate.deactivate()
        },

        computed: {
            autogeneratedName() {
                return [
                    'Viewshed',
                    moment(this.draftedOn).format('YYYYMMDDHHmm'),  // User's local timezone
                ].join(':')
            },

            canSubmit() {
                return this.source
                    && this.point
                    && this.radius
            },

            maxRadius() {
                const sourceType = SOURCE_ELEVATION  // FIXME -- compute this somehow
                return MAX_RADIUS[sourceType]
            },
        },

        filters: {
            rounded(n) {
                return Math.round(n * 1000) / 1000
            },
        },

        methods: {
            ...mapMutations({
                'onError': 'APPEND_ERROR',
            }),

            ...mapActions({
                'onAnalyticCreated': 'appendNewAnalytic',
            }),

            createAnalytic() {
                const request = {
                    'latitude':        this.point.latitude,
                    'longitude':       this.point.longitude,
                    'name':            this.name || this.autogeneratedName,
                    'observer_height': this.observerHeight,
                    'outer_radius':    this.radius,
                    'source':          this.source,
                    'target_height':   this.targetHeight,
                }

                console.debug('[Viewshed] Submitting request for processing:\n%s', JSON.stringify(request, null, 4))

                this.isSubmitting = true

                axios.post('/api/viewshed/create_analytic', request)
                    .then(response => {
                        this.draftedOn = moment.now()
                        this.isSubmitting = false

                        this.onAnalyticCreated(response.data.analytic)
                    })
                    .catch(err => {
                        this.isSubmitting = false

                        const {response} = err
                        if (response) {
                            this.onError({
                                heading: 'Could not create Viewshed analytic',
                                message: response.status >= 400 && response.status < 500
                                    ? `The server rejected your request: "${response.data.error}"`
                                    : `A server or network error prevented the submission of these records
                                       for processing.  If this problem persists, please contact an
                                       XTerrain administrator for technical support.`
                            })
                        }
                        else {
                            this.onError({
                                heading: 'Application error has occurred',
                                message: `An application error is preventing normal operation.  If this
                                          problem persists, please contact an XTerrain administrator for
                                          technical support.  (${err.message})`
                            })
                        }
                    })
            },

            onRecenterClick() {
                MapDelegate.recenter()
            },

            onObserverHeightChange(value) {
                this.observerHeight = value
            },

            onPointCreated({ latitude, longitude }) {
                this.point = { latitude, longitude }
            },

            onRadiusChange(value) {
                this.radius = value
            },

            onSourceChange(value) {
                this.source = value
            },

            onTargetHeightChange(value) {
                this.targetHeight = value
            },
        },

        watch: {
            point() {
                MapDelegate.renderPoint({
                    point: this.point,
                    radius: this.radius,
                })
            },
            radius() {
                if (!this.point) {
                    return  // Nothing to do
                }

                MapDelegate.renderPoint({
                    point: this.point,
                    radius: this.radius,
                })
            },
        },
    }
</script>

<style>
    .Viewshed__rowCaption,
    .Viewshed .SourceList__caption,
    .Viewshed .NumberRange__caption {
        display: block;
        margin-bottom: .25em;
        min-width: 100px;
    }

    .Viewshed__name input {
        width: 100%;
    }

    .Viewshed__pointCoordinates {
        /*margin-top: -20px;*/
        text-align: right;
        font-size: 24px;
        font-weight: 100;
    }

    .Viewshed__pointPlaceholder {
        display: block;
        color: #555;
        text-align: center;
    }

    .Viewshed__recenterButton {
        display: inline-block;
        margin-left: .5em;
        vertical-align: text-bottom;
        background-color: #263238;
        border: none;
        color: white;
        cursor: pointer;
        font-size: 14px;
        border-radius: 2px;
        width: 30px;
        height: 30px;
        text-align: center;
    }

    .Viewshed__recenterButton:hover {
        background-color: hsl(200, 40%, 25%);  /* Based on LimedSpruce */
    }

    .Viewshed__controls {
        padding: 30px;
        background-color: #1a2327;
        border-top: 1px solid #333;
        border-bottom: 1px solid #333;
    }

    .Viewshed__mapPointFootprint {
        animation: Viewshed__mapPointFootprint--blink infinite linear 3s;
        stroke-width: 2;
        stroke-dasharray: 10 10;
        /*fill: hsla(179, 21%, 61%, 1);  !* Based on GulfStream *!*/
        fill: hsla(179, 100%, 75%, .5);  /* Based on GulfStream */
        stroke: hsla(179, 100%, 75%, .7);  /* Based on GulfStream */
    }

    @keyframes Viewshed__mapPointFootprint--blink {
        from { fill-opacity: 1; stroke-dashoffset: 0; }
        to { fill-opacity: .2; stroke-dashoffset: 20; }
    }

    .Viewshed__loadingMask {
        z-index: 10;
    }
</style>
