<template>
    <div class="CostDistance">
        <SidePanel>
            <SourceList
                class="SidePanel__row"
                :source="source"
                :groups="SUPPORTED_SOURCES"
                :onChange="onSourceChange"
            />

            <div class="SidePanel__row CostDistance__point">
                <span class="CostDistance__rowCaption">Point</span>
                <span v-if="!point" class="CostDistance__pointPlaceholder">Click map anywhere to draw a point <i class="fa fa-arrow-right"/></span>

                <div v-if="point" class="CostDistance__pointCoordinates">
                    {{ point.longitude | rounded }}, {{ point.latitude | rounded }}

                    <button
                        class="CostDistance__recenterButton"
                        title="Show this point on the map"
                        @click="onRecenterClick">
                        <i class="fa fa-map-marker"/>
                    </button>
                </div>
            </div>

            <NumberRange
                class="SidePanel__row"
                caption="Distance"
                :step="0.025"
                :min="0.1"
                :max="2.0"
                :value="distance"
                :onChange="onDistanceChange"
            />

            <label class="SidePanel__row CostDistance__name">
                <span class="CostDistance__rowCaption">Analytic Name</span>
                <input v-model="name" :placeholder="autogeneratedName"/>
            </label>

            <div class="CostDistance__controls">
                <BigButton :disabled="!canSubmit" :onClick="createAnalytic">
                    Create Analytic
                </BigButton>
            </div>

            <RunningAnalyticsList/>
        </SidePanel>

        <LoadingMask
            class="CostDistance__loadingMask"
            caption="Submitting for processing.  Please wait."
            v-if="isSubmitting"
        />
    </div>
</template>

<script>
    import axios from 'axios'
    import moment from 'moment'
    import { mapActions, mapMutations } from 'vuex'

    import BigButton from '../BigButton.vue'
    import LoadingMask from '../LoadingMask.vue'
    import NumberRange from '../NumberRange.vue'
    import RunningAnalyticsList from '../RunningAnalyticsList.vue'
    import SidePanel from '../SidePanel.vue'
    import SourceList from '../SourceList.vue'

    import * as MapDelegate from './map-delegate'

    import {
        SOURCE_GROUP_FRICTION,
        MIN_ALTITUDE,
        MAX_ALTITUDE,
    } from '../../constants'


    export default {
        LABEL: 'Cost Distance',

        components: {
            BigButton,
            LoadingMask,
            NumberRange,
            RunningAnalyticsList,
            SidePanel,
            SourceList,
        },

        data() {
            return {
                MAX_ALTITUDE,
                MIN_ALTITUDE,
                SUPPORTED_SOURCES: [SOURCE_GROUP_FRICTION],
                draftedOn: moment.now(),
                isSubmitting: false,
                name: '',
                point: null,
                distance: 0.5,
                source: '',
            }
        },

        mounted() {
            MapDelegate.activate({
                onPointCreated: this.onPointCreated,
            })
        },

        beforeDestroy() {
            MapDelegate.deactivate()
        },

        computed: {
            autogeneratedName() {
                return [
                    'CostDistance',
                    moment(this.draftedOn).format('YYYYMMDDHHmm'),  // User's local timezone
                ].join(':')
            },

            canSubmit() {
                return this.source
                    && this.point
            },
        },

        filters: {
            rounded(n) {
                return Math.round(n * 1000) / 1000
            },
        },

        methods: {
            ...mapMutations({
                'onError': 'APPEND_ERROR',
            }),

            ...mapActions({
                'onAnalyticCreated': 'appendNewAnalytic',
            }),

            createAnalytic() {
                const request = {
                    'latitude':  this.point.latitude,
                    'longitude': this.point.longitude,
                    'name':      this.name || this.autogeneratedName,
                    'bbox':      MapDelegate.computeBounds(this.point, this.distance),
                    'source':    this.source,
                }

                console.debug('[CostDistance] Submitting request for processing:\n%s', JSON.stringify(request, null, 4))

                this.isSubmitting = true

                axios.post('/api/cost_distance/create_analytic', request)
                    .then(response => {
                        this.draftedOn = moment.now()
                        this.isSubmitting = false

                        this.onAnalyticCreated(response.data.analytic)
                    })
                    .catch(err => {
                        this.isSubmitting = false

                        const {response} = err
                        if (response) {
                            this.onError({
                                heading: 'Could not create CostDistance analytic',
                                message: response.status >= 400 && response.status < 500
                                    ? `The server rejected your request: "${response.data.error}"`
                                    : `A server or network error prevented the submission of these records
                                       for processing.  If this problem persists, please contact an
                                       XTerrain administrator for technical support.`
                            })
                        }
                        else {
                            this.onError({
                                heading: 'Application error has occurred',
                                message: `An application error is preventing normal operation.  If this
                                          problem persists, please contact an XTerrain administrator for
                                          technical support.  (${err.message})`
                            })
                        }
                    })
            },

            onRecenterClick() {
                MapDelegate.recenter()
            },

            onDistanceChange(distance) {
                this.distance = distance
            },

            onPointCreated({ latitude, longitude }) {
                this.point = { latitude, longitude }
            },

            onSourceChange(value) {
                this.source = value
            },
        },

        watch: {
            distance() {
                if (!this.point) {
                    return  // Nothing to do
                }

                MapDelegate.renderPoint({
                    point: this.point,
                    distance: this.distance,
                })
            },
            point() {
                MapDelegate.renderPoint({
                    point: this.point,
                    distance: this.distance,
                })
            },
        },
    }
</script>

<style>
    .CostDistance__rowCaption,
    .CostDistance .SourceList__caption,
    .CostDistance .NumberRange__caption {
        display: block;
        margin-bottom: .15em;
        min-width: 100px;
    }

    .CostDistance__name input {
        width: 100%;
    }

    .CostDistance__pointCoordinates {
        /*margin-top: -20px;*/
        text-align: right;
        font-size: 24px;
        font-weight: 100;
    }

    .CostDistance__pointPlaceholder {
        display: block;
        color: #555;
        text-align: center;
    }

    .CostDistance__recenterButton {
        display: inline-block;
        margin-left: .5em;
        vertical-align: text-bottom;
        background-color: #263238;
        border: none;
        color: white;
        cursor: pointer;
        font-size: 14px;
        border-radius: 2px;
        width: 30px;
        height: 30px;
        text-align: center;
    }

    .CostDistance__recenterButton:hover {
        background-color: hsl(200, 40%, 25%);  /* Based on LimedSpruce */
    }

    .CostDistance__controls {
        padding: 30px;
        background-color: #1a2327;
        border-top: 1px solid #333;
        border-bottom: 1px solid #333;
    }

    .CostDistance__mapPointFootprint {
        animation: CostDistance__mapPointFootprint--blink infinite linear 3s;
        stroke-width: 2;
        stroke-dasharray: 10 10;
        fill: hsla(179, 100%, 75%, .5);  /* Based on GulfStream */
        stroke: hsla(179, 100%, 75%, .7);  /* Based on GulfStream */
    }

    @keyframes CostDistance__mapPointFootprint--blink {
        from { fill-opacity: 1; stroke-dashoffset: 0; }
        to { fill-opacity: .2; stroke-dashoffset: 20; }
    }

    .CostDistance__loadingMask {
        z-index: 10;
    }
</style>
